"""
Schema description for the Online Retail analytics database.

This text is intended to be used in LLM prompts for SQL generation.
It documents the available tables and columns, their meanings,
and important business rules.
"""

SCHEMA_DESCRIPTION = """
You are working with a SQLite database for an online retail business.
All timestamps are in UTC and formatted as ISO-8601 strings.

The database currently has two main tables: transactions and customers.

TABLE: transactions
- Purpose: Stores individual line items for customer purchases.
- Granularity: One row per product line in an invoice.

Columns:
- id (INTEGER, PRIMARY KEY, AUTOINCREMENT)
    - Surrogate key for this table. Not used in business logic.
- InvoiceNo (TEXT)
    - Invoice number for the transaction.
    - A 6-digit code that uniquely identifies each invoice.
    - Cancellations with InvoiceNo starting with 'C' have already been removed,
      so only completed (non-cancelled) invoices remain.
- StockCode (TEXT)
    - Code of the product (item).
    - A nominal code that identifies a distinct product.
- Description (TEXT)
    - Human-readable name of the product.
- Quantity (INTEGER)
    - Quantity of the product purchased in this line.
    - Always positive in this table (cancellations/returns filtered out).
- InvoiceDate (TEXT)
    - Date and time when the invoice was generated.
    - Stored as a string in ISO format, e.g. '2010-12-01 08:26:00'.
- UnitPrice (REAL)
    - Price per single unit of the product, in GBP.
- CustomerID (INTEGER)
    - Unique identifier for the customer.
    - Same CustomerID appears in the customers table.
- Country (TEXT)
    - Country where the customer resides.
- Revenue (REAL)
    - Line-level revenue = Quantity * UnitPrice.
    - Because cancellations have been removed and quantities are positive,
      Revenue is always non-negative in this table.

Business rules for transactions:
- All cancellation / credit-note rows (InvoiceNo starting with 'C') are excluded.
- Negative quantities and non-positive prices have been filtered out before loading.
- Use this table for detailed time-series and product-level analyses,
  such as revenue over time, top products, or customer purchasing patterns.


TABLE: customers
- Purpose: Aggregated metrics per customer, derived from transactions.
- Granularity: One row per customer (CustomerID).

Columns:
- CustomerID (INTEGER, PRIMARY KEY)
    - Unique identifier of the customer.
- Country (TEXT)
    - Most frequent country for that customer (mode of transaction countries).
- first_purchase_date (TEXT)
    - The date/time of the customer's first recorded purchase.
    - ISO string, e.g. '2010-12-01 08:26:00'.
- last_purchase_date (TEXT)
    - The date/time of the customer's most recent recorded purchase.
- num_transactions (INTEGER)
    - Number of distinct invoices (InvoiceNo) for this customer.
    - This is the count of unique orders, not line items.
- total_quantity (INTEGER)
    - Total units purchased across all transactions for this customer.
- total_revenue (REAL)
    - Total revenue generated by this customer across all transactions.
    - Sum of Revenue from the transactions table for this customer.
- avg_order_value (REAL)
    - Average revenue per invoice for this customer.
    - Calculated as total_revenue / num_transactions when num_transactions > 0.

Business rules for customers:
- All aggregates are computed from the transactions table AFTER filtering out
  cancellations and invalid rows.
- The first_purchase_date and last_purchase_date come from the earliest and latest
  InvoiceDate values for that customer's invoices.
- Use this table for customer-level analytics, segmentation, and as a basis for
  CLV, churn, survival analysis, and uplift modeling.

General guidance for SQL:
- For product-level questions (e.g., top products by revenue), use the transactions table.
- For customer-level questions (e.g., total revenue per customer, top customers),
  use the customers table, possibly joining with transactions if you need time details.
"""
